services:
    _defaults: { autowire: true, autoconfigure: true, public: true }

    # Excel export
    Markocupic\RszPraesenzkontrolleBundle\BenutzerverwaltungBundle\Excel\RszPraesenzkontrolleDownload: ~


