services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
        bind:
            #$projectDir: '%kernel.project_dir%'

    Markocupic\RszPraesenzkontrolleBundle\:
        resource: ../src/
        exclude: ../src/{DependencyInjection}
